import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import sharp from 'sharp'
import { routes } from '../src/routes.js'
import { contact, siteOrigin } from '../src/data/site.js'
import { posts } from '../src/data/generated/posts.js'
import { blogSeo, postShareImage } from '../src/data/seo.js'

const root = resolve(import.meta.dirname, '..')
const dist = resolve(root, 'dist')
const ssrEntry = pathToFileURL(resolve(root, 'dist-ssr/entry-server.js')).href

const { render } = await import(ssrEntry)
const template = await readFile(resolve(dist, 'index.html'), 'utf8')

const escape = (value) =>
  String(value ?? '').replace(/[&<>'"]/g, (ch) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[ch])

// A purpose-built 1200x630 card, regenerated by scripts/make-og-card.mjs. PNG
// rather than the site's webp because LinkedIn's crawler does not render webp,
// and 1.91:1 so platforms show it whole instead of cropping the logo. Posts
// swap in their own card (see postShareImage), converted below.
const defaultImage = { path: '/og-card.png', type: 'image/png', alt: 'Wavefront Studio' }
const OG_IMAGE_WIDTH = 1200
const OG_IMAGE_HEIGHT = 630

function buildHead({ title, description, canonical, schema, ogType = 'website', published, modified, image }) {
  const url = `${siteOrigin}${canonical || '/'}`
  const share = image ? { path: image, type: 'image/jpeg', alt: title } : defaultImage
  const imageUrl = `${siteOrigin}${share.path}`
  const parts = [
    '<meta property="og:site_name" content="Wavefront Studio" />',
    '<meta property="og:locale" content="en_US" />',
    `<meta property="og:title" content="${escape(title)}" />`,
    `<meta property="og:description" content="${escape(description)}" />`,
    `<meta property="og:url" content="${url}" />`,
    `<meta property="og:type" content="${ogType}" />`,
    `<meta property="og:image" content="${imageUrl}" />`,
    // Stated up front so a card renders at the right size before the crawler
    // has finished fetching the image.
    `<meta property="og:image:width" content="${OG_IMAGE_WIDTH}" />`,
    `<meta property="og:image:height" content="${OG_IMAGE_HEIGHT}" />`,
    `<meta property="og:image:type" content="${share.type}" />`,
    `<meta property="og:image:alt" content="${escape(share.alt)}" />`,
    '<meta name="twitter:card" content="summary_large_image" />',
    `<meta name="twitter:title" content="${escape(title)}" />`,
    `<meta name="twitter:description" content="${escape(description)}" />`,
    `<meta name="twitter:image" content="${imageUrl}" />`,
  ]
  if (ogType === 'article') {
    if (published) parts.push(`<meta property="article:published_time" content="${published}" />`)
    if (modified) parts.push(`<meta property="article:modified_time" content="${modified}" />`)
  }
  if (schema) {
    // The id matters: the browser-side useSeo looks for it and updates this
    // script in place. Without it the page ends up with two copies once the
    // app loads, and Search Console reports duplicate FAQPage markup.
    parts.push(`<script type="application/ld+json" id="route-jsonld">${JSON.stringify(schema).replace(/</g, '\\u003c')}</script>`)
  }
  return parts.join('')
}

// Social cards for posts: a 1200x630 JPEG beside each 2400x1260 webp card.
for (const post of posts) {
  const share = postShareImage(post)
  if (!share) continue
  const target = resolve(dist, `.${share}`)
  await mkdir(dirname(target), { recursive: true })
  await sharp(resolve(root, `public${post.image}`))
    .resize(OG_IMAGE_WIDTH, OG_IMAGE_HEIGHT)
    .jpeg({ quality: 82, mozjpeg: true })
    .toFile(target)
}

const pages = []

for (const route of routes) {
  let rendered
  try {
    rendered = await render(route.path)
  } catch (error) {
    // Usually a scheduled page whose date has arrived before its content was
    // added (src/data/schedule.js). Failing the build keeps the last good
    // deploy live instead of publishing a broken page.
    throw new Error(`Could not render ${route.path}: ${error.message}`)
  }
  const { html, seo } = rendered
  const title = seo.title || 'Wavefront Studio LLC'
  const description = seo.description || ''
  const canonical = seo.canonical || route.path

  // The social tags and JSON-LD go straight after the canonical link, ahead of
  // the tracking scripts. Google stops reading <head> at the first element it
  // does not expect there, so anything important sits as early as possible.
  const page = template
    .replace(/<title>.*?<\/title>/s, `<title>${escape(title)}</title>`)
    .replace(/<meta name="description" content=".*?"\s*\/>/s, `<meta name="description" content="${escape(description)}" />`)
    .replace(
      /<link rel="canonical" href=".*?"\s*\/>/s,
      `<link rel="canonical" href="${siteOrigin}${canonical}" />${buildHead({ ...seo, title, description, canonical })}`,
    )
    .replace('<div id="root"></div>', `<div id="root">${html}</div>`)

  const target = route.path === '/' ? resolve(dist, 'index.html') : resolve(dist, `.${route.path}index.html`)
  await mkdir(dirname(target), { recursive: true })
  await writeFile(target, page)
  pages.push({ path: route.path, kind: route.kind, title, description, modified: seo.modified })
}

// A 404 fallback that still ships the app shell, so a static host can serve it
// for unknown paths and the client router renders the not-found page.
const { html: notFoundHtml, seo: notFoundSeo } = await render('/__not-found__')
await writeFile(
  resolve(dist, '404.html'),
  template
    .replace(/<title>.*?<\/title>/s, `<title>${escape(notFoundSeo.title)}</title>`)
    .replace(/<meta name="description" content=".*?"\s*\/>/s, `<meta name="description" content="${escape(notFoundSeo.description)}" />`)
    .replace(/<link rel="canonical" href=".*?"\s*\/>/s, '<meta name="robots" content="noindex, follow" />')
    .replace('<div id="root"></div>', `<div id="root">${notFoundHtml}</div>`),
)

// lastmod only where the date is real. Stamping every URL with the build date
// teaches Google to ignore the field, so pages without a known date leave it out.
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages
  .map(({ path, modified }) => `  <url><loc>${siteOrigin}${path}</loc>${modified ? `<lastmod>${modified}</lastmod>` : ''}</url>`)
  .join('\n')}
</urlset>
`
await writeFile(resolve(dist, 'sitemap.xml'), sitemap)

await writeFile(
  resolve(dist, 'robots.txt'),
  `User-agent: *\nAllow: /\n\nSitemap: ${siteOrigin}/sitemap.xml\n`,
)

// RSS for the blog. The old WordPress /feed/ redirects here (vercel.json).
const newestFirst = [...posts].sort((a, b) => b.date.localeCompare(a.date))
const rfc822 = (iso) => new Date(`${iso}T12:00:00Z`).toUTCString()
const rss = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<title>Wavefront Studio Blog</title>
<link>${siteOrigin}/blog/</link>
<atom:link href="${siteOrigin}/rss.xml" rel="self" type="application/rss+xml" />
<description>${escape(blogSeo.description)}</description>
<language>en-us</language>
<lastBuildDate>${rfc822(newestFirst[0].date)}</lastBuildDate>
${newestFirst
  .map((post) => {
    const url = `${siteOrigin}/${post.slug}/`
    return `<item><title>${escape(post.title)}</title><link>${url}</link><guid isPermaLink="true">${url}</guid><pubDate>${rfc822(post.date)}</pubDate><description>${escape(post.excerpt)}</description></item>`
  })
  .join('\n')}
</channel>
</rss>
`
await writeFile(resolve(dist, 'rss.xml'), rss)

// llms.txt: a plain map of the site for AI assistants, written from the same
// titles and descriptions the pages carry so it cannot drift out of date.
const byPath = Object.fromEntries(pages.map((page) => [page.path, page]))
const shortTitle = (title) => title.replace(/\s*[|–—-]\s*Wavefront Studio(?: LLC)?$/, '')
const entry = (path, name) => `- [${name || shortTitle(byPath[path].title)}](${siteOrigin}${path}): ${byPath[path].description}`
const ofKind = (kind) => pages.filter((page) => page.kind === kind)
const llms = [
  '# Wavefront Studio LLC',
  '',
  '> Wavefront Studio LLC is a full-service digital agency based in Sarasota, Florida and serving clients worldwide. The company builds websites, mobile apps, search strategies, digital marketing systems, AI-assisted customer experiences, and custom business tools.',
  '',
  `Address: 4363 Independence Ct, Sarasota, FL 34234, United States. Phone: ${contact.supportPhone}. Email: ${contact.email}.`,
  '',
  '## Services',
  '',
  entry('/services/', 'All digital services'),
  ...ofKind('service').map((page) => entry(page.path)),
  '',
  '## Custom tools',
  '',
  entry('/custom-works/', 'All custom works'),
  ...ofKind('custom-work').map((page) => entry(page.path)),
  '',
  '## Free tools and offers',
  '',
  entry('/lost-lead-calculator/'),
  entry('/package-builder/'),
  entry('/free-setup/'),
  '',
  '## Service areas',
  '',
  entry('/locations/', 'Where we work'),
  ...ofKind('location').map((page) => entry(page.path)),
  '',
  ...(ofKind('state').length ? ['## State guides', '', ...ofKind('state').map((page) => entry(page.path)), ''] : []),
  '## Blog',
  '',
  ...newestFirst.map((post) => entry(`/${post.slug}/`, post.title)),
  '',
  '## Company',
  '',
  entry('/about/', 'About Wavefront Studio'),
  entry('/portfolio/', 'Portfolio'),
  entry('/faqs/', 'Frequently asked questions'),
  entry('/contact/', 'Contact'),
  '',
].join('\n')
await writeFile(resolve(dist, 'llms.txt'), llms)

await rm(resolve(root, 'dist-ssr'), { recursive: true, force: true })

console.log(`Prerendered ${pages.length} pages + 404 + sitemap.xml, rss.xml, llms.txt`)
